// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/qiangyt/jog/server/biz"
	"github.com/qiangyt/jog/server/conf"
	"github.com/qiangyt/jog/server/data"
	"github.com/qiangyt/jog/server/service"
)

// Injectors from wire.go:

// initServer init Jog Server with kratos application.
func initServer(logger log.Logger, serverVersion ServerVersion, bootstrap *conf.Bootstrap, server *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, logger)
	httpServer := NewHTTPServer(server, greeterService, logger)
	grpcServer := NewGRPCServer(server, greeterService, logger)
	app := NewServer(logger, serverVersion, bootstrap, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
